### ISSUE TITLE
[sed-4.4-x64.exe] error when using "sed -i"

### ISSUE THREAD

**Issue by dnmTX** [mbuilov/sed-windows#1]
@mbuilov 
Trying to edit .bat file using "sed -i" and every time i get this error:
**sed-4.4-x64: cannot rename ./sed8JEw8l: Improper link**
Can you please provide some input,maybe workaround.Thank you.
Windows 10 1607 LTSB

**Comment by mbuilov** [comment]
Thank you for the bug report.
There is windows-specific bug in sed/execute.c, function open_next_file().
For the case of in-place substitution, it computes path to the temporary directory by searching symbol '/' in the path to the input file.
But normally, windows paths do not contain forward slashes, e.g.: C:\a\b\c\file.txt.
So, open_next_file() falls back to use '.' (current directory) as temporary dir.

Now suppose editing file is on other disk:
C:\User>sed-windows\sed-4.4.exe -i "" d:\edit.bat
The command fails with:
sed-windows\sed-4.4.exe: cannot rename ./sed1hfX6f: Improper link

But, if i change backward slashes in the path to editing file:
C:\User>sed-windows\sed-4.4.exe -i "" d:/edit.bat
The command succeeds.

**Comment by dnmTX** [comment]
@mbuilov  wow,changing it to "/ " did the job.I almost lost hope,couldn't find any info on the net,good thing that you replied here(thank you).It's probably a good idea if  you add a disclaimer or something on the front page for the others stuck individuals like myself.Turns out that the bug only occur when doing it from cmd. In batch, with properly set working directory ("cd /d") everything works as intended.Thanks again for the prompt reply and the help 👍 
Closing......
