### ISSUE TITLE
publish the .exe to the "Releases" section

### ISSUE THREAD

**Issue by virtualex-itv** [mbuilov/sed-windows#11]
Currently, these `.exe` files are on the root of your repo.  Can you please create a release for the 4.9 version and any future releases so they can be downloaded as "assets", please?  This will help make it easier to maintain a chocolatey installation package for this application anytime you release a new version.

**Comment by mbuilov** [comment]
I hope I did it right.

**Comment by sitiom** [comment]
Thanks! I have now added the sed build to Winget:

- https://github.com/microsoft/winget-pkgs/pull/122053

It should now be installable with `winget install mbuilov.sed`. Winget Releaser should be set up in this repo for updates: #14
