### ISSUE TITLE
sed 4.9 show (with --version) version 4.2.1

### ISSUE THREAD

**Issue by bovirus** [mbuilov/sed-windows#12]
@mbuilov 

Download Windows 10 x64 e x86 exe file.

Run it in DOS prompt with "--version" option and show it as 4.2.1.

Is it normal?

Thanks.

**Comment by mbuilov** [comment]
Hi, please make sure you have downloaded sed-4.9 executables from "https://github.com/mbuilov/sed-windows" or "https://github.com/mbuilov/sed-windows/releases".

**Comment by bovirus** [comment]
@mbuilov 

You are right.
I downloaded again thee exe file and now it works right.
Thanks. Please close the issue.
