### ISSUE TITLE
Optimse windows build steps?

### ISSUE THREAD

**Issue by Cube707** [mbuilov/sed-windows#13]
I experimente around with building `sed` on windows today and found the following which might be interesting:

MingGW actually supports `_FORTIFY_SOURCE` and therefor the patching step could be optimized. Running this works fine for me without modifying `config.h`:

```bash
./configure --host=x86_64-w64-mingw32 --disable-nls CFLAGS=-fstack-protector
make
```

See also: <https://sourceforge.net/p/mingw-w64/mailman/mingw-w64-public/thread/a6f47044-8c7a-8597-a586-0e6ecb089bd7%40t-online.de/#msg36747706>

Sidenote:  I am building from within WSL (not via MSYS), so I am not sure if it translates.

**Comment by mbuilov** [comment]
Thanks, it looks like _FORTIFY_SOURCE is now supported by newer migw64 versions.

I created sed-4.9-build-MINGW.txt - without deleting _FORTIFY_SOURCE and with CFLAGS="-g -O2 -fstack-protector".

Note that CFLAGS are specified with "-g -O2", otherwise sed will be compiled without optimizations.

**Comment by Cube707** [comment]
good hint with the optimisation. 

closing this as complete
