### ISSUE TITLE
sed-4.9-x64 works with error

### ISSUE THREAD

**Issue by baal793** [mbuilov/sed-windows#18]
```
@echo off
>  list.txt echo 1
>> list.txt echo 2
>> list.txt echo 3
>> list.txt echo 3
>> list.txt echo 2
>> list.txt echo 1
set "sedUniqLines=h;:b;$b;N;/^\(.*\)\n\1$/ {g;bb;};$b;P;D"
sort list.txt | sed-4.9-x64.exe -e "%sedUniqLines%" > list_unique_x64.txt
sort list.txt | sed-4.9-x86.exe -e "%sedUniqLines%" > list_unique_x86.txt
```

list_unique_x64.txt:
1
1
2
2
3
3

list_unique_x86.txt:
1
2
3

GNU sed for windows 4.2.1 from https://gnuwin32.sourceforge.net/packages/sed.htm works fine

**Comment by mbuilov** [comment]
Thank you, I found an error - the configure script incorrectly determined the ssize_t type for the x86_64 platform - as int.

ssize_t under x86_64 should be defined as __int64.

I have reassembled sed-4.9-x64.exe .

**Comment by baal793** [comment]
Thank you too! Everything works fine now.
