### ISSUE TITLE
Bug parsing binary data in Chinese environment

### ISSUE THREAD

**Issue by ner00** [mbuilov/sed-windows#2]
This version of sed (v4.3-v4.5) introduces a bug in processing binary data - something which so far only seems to be a problem under Chinese Windows environment. Take for example a file containing the following binary data:

`E9 1F 00 00 00 CC CC CC CC CC CC CC CC CC CC CC CC CC CC CC CC CC CC CC CC CC`

Then, consider the following command:

`sed -b s/\xE9\x1F\x00\x00\x00\xCC\xCC\xCC\xCC\xCC\xCC\xCC\xCC\xCC\xCC\xCC\xCC\xCC\xCC\xCC\xCC\xCC\xCC\xCC\xCC\xCC/\xE9\x1F\x00\x00\x00\x3D\x00\x00\x43\x44\x0F\x84\xFE\xCE\x04\x00\x48\x8B\x7C\x24\x60\xE9\x6D\x00\xDC\xFF/g hex1 > hex2`

When using one of these builds, with a traditional Chinese version of Windows, the output file suffers no replacement of bytes whatsoever. If I use the same version of sed under, let's say, a US or French version of Windows, it works flawlessly. Furthermore, this issue with a Chinese environment does not happen with v4.2.1. This is just an example, there are other combinations of bytes which are incorrectly parsed when using a Chinese command prompt.

**Comment by mbuilov** [comment]
Thank you for the bug report.

I have reproduced the bug after changing windows 10 interface language to chinese.
And, surprisingly, x64-version (sed-4.5-x64.exe) works as expected.
Looks like only x86-version (sed-4.5.exe) built by Visual Studio 2008 contains the bug.

**Comment by ner00** [comment]
> 
> 
> Thank you for the bug report.
> 
> I have reproduced the bug after changing windows 10 interface language to chinese.
> And, surprisingly, x64-version (sed-4.5-x64.exe) works as expected.
> Looks like only x86-version (sed-4.5.exe) built by Visual Studio 2008 contains the bug.

I'm afraid that is incorrect.
Changing the language interface is insufficient to reproduce this issue.
I did that and was under the same impression, but had reports that the problem persisted.
Only after installing Windows 10 (x64) on a VM with Chinese as the base language was I able to see that the problem persists across multiple variants. I even installed the one packaged with CygWin, but that one also has some problems similar to yours, where, for example, it cannot replace patterns like this under the Chinese environment:

`sed-4.5-x64 -b s/\x89\x0D\x2A\x1E\x6B/\xAA\xBB\xCC\xDD\xEE/ hex1 > hex2`

I tried enclosing `\x2A` in `[ ]` to no avail.

**Comment by mbuilov** [comment]
I can confirm, changing
HKLM\SYSTEM\CurrentControlSet\Control\Nls\CodePage\OEMCP\ACP
from 1251 to 936 on my test Windows 10 x64 VM (after reboot) reveals the bug in the sed-4.5-x64.exe too...

Sed interprets regular expressions according to the current locale, even if the expression is written in hex form like /\x89\x0D\x2A\x1E\x6B/\xAA\xBB\xCC\xDD\xEE/.

Internally, while parsing regex, sed converts it from multibyte encoding (e.g. from 936 code page in our case) to wide-character string. And it seems some of characters are converted wrongly.

**Comment by mbuilov** [comment]
I have added -C (or --ignore-locale) switch to sed.
By this switch, sed ignores system locale and operates in the default "C" locale, processing input characters just as bytes.

**Comment by ner00** [comment]
Great!
Thanks for doing this so quickly.
I wonder if this also happens on Linux or if it's Windows specific.
Anyway, amazing job, @mbuilov

**Comment by mbuilov** [comment]
> Great!
> Thanks for doing this so quickly.
> I wonder if this also happens on Linux or if it's Windows specific.
> Anyway, amazing job, @mbuilov

Linux is also affected - this is locale specific behavior.
But on Windows, it's not so easy to run a console app in a specific locale...
Comparing to Linux, where you can just type:
$ env LC_ALL=C sed ....

I was glad to help :)
