### ISSUE TITLE
sed-4.7.exe cannot use * in filename

### ISSUE THREAD

**Issue by jack6th** [mbuilov/sed-windows#3]
`sed-4.7.exe -n 1p *.txt`

sed-4.7.exe: can't read *.txt: Invalid argument

**Comment by mbuilov** [comment]
Thanks for the bug report!
Yes, under Windows, each console program should expand wildcards in file names by yourself.
(Under Unix, the shell expands wildcards before passing arguments to a program).

I have patched sed sources and rebuilt executables - try them!
