### ISSUE TITLE
Doesn't work for me with UTF-8 

### ISSUE THREAD

**Issue by xoviat** [mbuilov/sed-windows#4]
Doesn't work for me with UTF-8 if I specify the script (containing multi-byte chars) directly on command line and redirect the output to a file. OTOH it works if using script file with the same chars. Demo:

![image](https://user-images.githubusercontent.com/49173759/70271086-5a2c1780-176b-11ea-8fce-92af69a770d2.png)

(from https://chocolatey.org/packages/sed#comment-4709869071)

**Comment by mbuilov** [comment]
Thanks for the bug report.
And sorry for the delay in responding.

In fact, sed is compiled without wide-character support, and the system converts command-line arguments from console encoding to ANSI code page, such as 1251.
Thus, you can set any console encoding via chcp, but sed will always receive arguments in the ANSI code page.

**Comment by xoviat** [comment]
Would it be possible to compile with wide-character support or is that too difficult?

**Comment by mbuilov** [comment]
Yes, it’s possible and I’m working on it.
Support for sed to work in the Windows console in UTF-8 (65001) encoding requires writing a bit of code to bypass known problems with input/output to the console.
I will also add the ability to specify the locale in which sed will work through the environment variables LC_ALL, LC_CTYPE and LANG.
Now the native version of sed always uses the OEM locale with ANSI code page (e.g. Russian_Russia.1251).
And finally, I will try to fix bugs in the support of UTF-8 locale (for example, sed will be able to work in the Russian_Russia.UTF-8 locale).

**Comment by mbuilov** [comment]
Ok, I think the issue now may be closed.
Please try a new version of sed-4.7-x64.exe.

If you want to get utf-8 string on sed output, run it with the environment variable "LC_ALL=.UTF-8".
If the output goes to the console, then internally utf-8 output sed will convert to Unicode (UTF16), and then (by the system) it will be converted to the console encoding.
The sed receives input from the console also in Unicode, and then converts it to the locale encoding.

**Comment by Dimsok** [comment]
Is it possible to get sed-4.9-xp.exe works with utf8?

**Comment by sergeevabc** [comment]
@mbuilov, I believe this issue is not fully resolved.

Windows 7 SP1 x64, sed 4.9, [hello.txt.zip](https://github.com/user-attachments/files/19219018/hello.txt.zip)

``` console

$ type hello.txt
Test

Проверка связи

$ sed.exe -e "1,2d" hello.txt
ÐŸÑ€Ð¾Ð²ÐµÑ€ÐºÐ° ÑÐ²ÑÐ·Ð¸
```

Changing `chcp` to 866, 1251 or 65001 does not help.

Now let's try other implementations.

[Busybox][1]'s sed.

```
$ busybox.exe sed -e "1,2d" hello.txt
Проверка связи
```

[MSYS2][2]'s sed 4.8.

```
$ sed.exe -e "1,2d" hello.txt
Проверка связи
```

[1]: https://frippery.org/busybox/
[2]: https://sourceforge.net/projects/mwayne/files/MSYS2Portable/

**Comment by mbuilov** [comment]
Попробуйте указать локаль явно:

```
>chcp
Active code page: 65001

>type 1.txt
Test

Проверка связи

>sed-4.9-x64.exe --locale=.utf8 -e "1,2d" 1.txt
Проверка связи
```

**Comment by sergeevabc** [comment]
> Попробуйте указать локаль явно

Работает. Так может быть сделать это поведением по умолчанию? А то надо ключ помнить и само написание локали (с точкой и без дефиса, т.е. не utf-8, не utf8, а .utf8) — чокнуться можно, учитывая, что sed это программа, к которой обращаешься от случая к случаю, а не гоняешь её ежедневно.

**Comment by mbuilov** [comment]
```
По-умолчанию в виндах локаль "Russian_Russia.1251".
Для sed'а - локаль определяет кодировку файлов.
Исторически сложилось, что в виндах файлы с русскими буквами - в cp1251.

Примеры:

1)
>chcp 65001
Active code page: 65001
>type 1-utf8.txt
Test

Проверка связи
>sed-4.9-x64.exe --locale=Russian_Russia.utf-8 -e "1,2d" 1-utf8.txt
Проверка связи
>sed-4.9-x64.exe --locale=Russian_Russia.utf8 -e "1,2d" 1-utf8.txt
Проверка связи
>sed-4.9-x64.exe --locale=.utf8 -e "1,2d" 1-utf8.txt
Проверка связи
>sed-4.9-x64.exe --locale=.utf-8 -e "1,2d" 1-utf8.txt
Проверка связи

При указании локали имя перед точкой может быть опущено - будет использовано имя локали по-умолчанию, т.е. Russian_Russia. 

2)
>chcp 1251
Текущая кодовая страница: 1251
>type 1-utf8.txt
Test

РџСЂРѕРІРµСЂРєР° СЃРІСЏР·Рё
>sed-4.9-x64.exe --locale=Russian_Russia.utf-8 -e "1,2d" 1-utf8.txt
Проверка связи
и т.д., как в 1)
Т.е. локаль - соответствует кодировке файла, а не консоли.
Тут консоль (в 1251) не умеет отображать utf8, поэтому "type 1-utf8.txt" показывает кракозябры.

А если попробовать файл в cp1251:
>type 1-cp1251.txt
Test

Проверка связи
>sed-4.9-x64.exe --locale=.utf-8 -e "1,2d" 1-cp1251.txt
sed-4.9-x64.exe: failed to write to console: cannot to convert character (LC_CTYPE=Russian_Russia.utf8 -> Unicode): Illegal byte sequence
Т.е. внутри sed работает с юникодом:
>sed-4.9-x64.exe --locale=.1251 -e "1,2d" 1-cp1251.txt
Проверка связи

Почему консоль во всех случаях отображает вывод sed'а правильно - потому что sed внутри работает в юникоде - на вход в устройство консоли подаётся юникод - консоль его преобразует в свою кодировку для отображения.

Но прежде всего, sed'у нужно преобразовать файл в юникод - для этого нужно как-то указать кодировку файла.

Тут есть ещё один нюанс - sed'у нужно также преобразовать аргументы командной строки в юникод - но с этим должен справиться рантайм винды - функция main под винду объявлена как "int wmain (int argc, wchar_t **wargv)".

------

Насчёт сделать utf-8 для sed'а локалью по-умолчанию - в коде это сделать можно, но тогда перестанут работать скрипты тех, кто заложился на локаль по-умолчанию (т.е. на .1251).

Можно собрать какой-нибудь sed-utf8.exe, а можно и обойтись батником:

>type sed-utf8.bat
@echo off
sed-4.9-x64.exe --locale=.utf8 %*

>sed-utf8.bat -e "1,2d" 1-utf8.txt
Проверка связи

>sed-utf8.bat -e "1,2d" 1-cp1251.txt
sed-4.9-x64.exe: failed to write to console: cannot to convert character (LC_CTYPE=Russian_Russia.utf8 -> Unicode): Illegal byte sequence
```

**Comment by mbuilov** [comment]
Почему указывается локаль с точкой, т.е. ".utf8" - потому, что локаль это не только про кодировку, но и про сравнение букв, преобразование в верхний и нижний регистр, про правила определения к какому классу относится символ (это пробел, пунктуация и т.д.), в общем - man locale.

Каждый из этих параметров LC_CTYPE, LC_COLLATE и т.д. можно настроить отдельно, а можно все вместе общей настройкой - через LC_ALL.

Т.к. в виндах бывает неудобно указывать локаль для программы через переменные окружения (LC_ALL, LC_CTYPE, LC_COLLATE и т.д), для sed'а я сделал ключ "--locale".

Да и, на сколько я помню, на виндах по-умолчанию программы не смотрят в переменные окружения при настройке локали по-умолчанию (вызовом setlocale(LC_ALL, "")) - делать проверку переменных окружения каждой программе нужно самостоятельно.

Все локаль-специфичные функции (вроде преобразования регистра символов) sed не реализует сам, а делает это вызовом API операционной системы.

Соответственно, нужно операционной системе указать локаль так, чтобы она её поняла:
```
>sed-4.9-x64.exe --locale=x.1251 -e "1,2d" 1-cp866.txt
sed: Bad locale name specified by the option '--locale'
```

См. `https://learn.microsoft.com/ru-ru/cpp/c-runtime-library/reference/setlocale-wsetlocale`

```
>sed-4.9-x64.exe --locale=ru-RU -e "1,2d" 1-cp1251.txt
Проверка связи
>sed-4.9-x64.exe --locale=Russian_Russia.ACP -e "1,2d" 1-cp1251.txt
Проверка связи
>sed-4.9-x64.exe --locale=Russian_Russia.OCP -e "1,2d" 1-cp866.txt
Проверка связи
>sed-4.9-x64.exe --locale=ru-RU.utf-8 -e "1,2d" 1-utf8.txt
Проверка связи
```

**Comment by sergeevabc** [comment]
Разбирался на днях с [программой](https://github.com/bol-van/zapret/issues/1271#issuecomment-2746396011), имеющей юниксовые корни и зависящей от cygwin. Она упорно не принимала путь с русскими буквами при запуске из командной строки. при этом прекрасно работала в качестве сервиса. Начал проверять переменные окружения, сравнивать пользовательские и системные. Среди пользовательских переменных у меня нашлась LANG=EN. Вероятно, я когда-то вписал её, чтобы некая программа отобразилась на английском языке. Тогда вместо EN указал en_GB.UTF-8 и всё заработало, русские пути считались. И сейчас вот проверяю ваш sed, тоже работает, даже без указания локали через ключ:

``` console
$ type hello.txt
Test

Проверка связи

$ sed.exe -e "1,2d" hello.txt
Проверка связи
```

Жизнь налаживается!
