### ISSUE TITLE
Build failure at final linking stage

### ISSUE THREAD

**Issue by oldpink** [mbuilov/sed-windows#5]
I applied the current patches for sed 4.7, then proceeded to attempt building with Mingw64 on Linux, but it fails at the final link, with the output shown below:

make[2]: Entering directory '/root/Downloads/sed-4.7'
  CCLD     sed/sed.exe
/opt/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/4.9.0/../../../../x86_64-w64-mingw32/lib/../lib/libmingw32.a(lib64_libmingw32_a-crt0_c.o): In function `main':
/home/mingw-w64/mingw-w64/linux-x86_64-x86_64/build/build/mingw/obj/../../../build/mingw/mingw-w64-crt/crt/crt0_c.c:18: undefined reference to `WinMain'
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:2453: sed/sed.exe] Error 1
make[2]: Leaving directory '/root/Downloads/sed-4.7'
make[1]: *** [Makefile:2908: all-recursive] Error 1
make[1]: Leaving directory '/root/Downloads/sed-4.7'
make: *** [Makefile:2148: all] Error 2

I have no idea how to correct this, even after having scanned the web for quite some time.

**Comment by mbuilov** [comment]
Thanks for the bug report.
The last patches assume that under Windows, sed is built as a unicode application.
And to build sed with mingw, gcc needs additional "-municode" option - see https://sourceforge.net/p/mingw-w64/wiki2/Unicode%20apps/

I have successfully built sed with the following instructions:
(in sed-windows directory)
1) tar xf ../sed-4.7.tar.xz && cd sed-4.7
2) patch -Np1 -i ../sed-4.7-src.patch
3) sed -i 's/^sed_sed_LINK = $(CCLD)/& -municode/' Makefile.in
4) sed -i '/^SUBDIRS = /s/ gnulib-tests/# gnulib-tests/' Makefile.in
5) ./configure --disable-dependency-tracking --disable-nls
6) make

**Comment by oldpink** [comment]
It builds and runs perfectly using those two sed commands.
Thank you!
Also, thank you for maintaining these patches for the world at large.
I use your patched sed at work on a Windows 10 platform to maintain our employee lists on a daily basis.
