### ISSUE TITLE
Not an issue...only a request

### ISSUE THREAD

**Issue by oldpink** [mbuilov/sed-windows#6]
I don't know if the maintainer of these excellent patches are aware of it yet, but SED version 4.8 has been out for almost two weeks; so are there any plans to adapt a set of patches for the new version?
Not that version 4.7 is inadequate, but it would be cool to be able to use the new version.

**Comment by mbuilov** [comment]
Thanks, I am aware now :)
I plan to adapt the patches for sed 4.8 on next week.

**Comment by oldpink** [comment]
Great!
Again, allow me to take this opportunity to give you a huge thanks for maintaining your excellent patches.
Without your patches, I wouldn't be able to use sed at work to automate our employee database.
