### ISSUE TITLE
x64 is 2x~3x slower than x86

### ISSUE THREAD

**Issue by jack6th** [mbuilov/sed-windows#7]
$ dir sed*.exe  
sed-4.8-x64.exe  
sed-4.8-xp.exe  

$ type test.cmd  
```
@echo off
(for /l %%i in (1,1,100000) do echo %%i) > a.txt
call :test sed-4.8-xp
call :test sed-4.8-x64
pause
goto :eof

:test
echo %1
echo %time%
%1 "N;s/\n/, /" a.txt > %1.txt
echo %time%
echo.
goto :eof
```
$ test.cmd  
sed-4.8-xp  
11:31:17.99  
11:31:18.07  
  
sed-4.8-x64  
11:31:18.07  
11:31:18.33

**Comment by mbuilov** [comment]
Thank you for the bug report.

But I can't reproduce the issue.
On my Window7 laptop, I don't see much difference:

in the cmd.exe window:

```
1) cmd.exe /s /c "(for /l %i in (1,1,1000000) do @echo %i) > a.txt"
2) for /l %i in (1,1,5) do (c:\cygwin64\bin\bash -c "time cmd.exe /s /c \"\"sed-4.8-xp.exe \"N;s/\n/, /\" a.txt \> b.txt\"\"")

c:\sed-windows>(c:\cygwin64\bin\bash -c "time cmd.exe /s /c \"\"sed-4.8-xp.exe \"N;s/\n/, /\" a.txt \> b.txt\"\"" )

real    0m2.481s
user    0m0.000s
sys     0m0.031s

c:\sed-windows>(c:\cygwin64\bin\bash -c "time cmd.exe /s /c \"\"sed-4.8-xp.exe \"N;s/\n/, /\" a.txt \> b.txt\"\"" )

real    0m1.716s
user    0m0.000s
sys     0m0.015s

c:\sed-windows>(c:\cygwin64\bin\bash -c "time cmd.exe /s /c \"\"sed-4.8-xp.exe \"N;s/\n/, /\" a.txt \> b.txt\"\"" )

real    0m1.388s
user    0m0.000s
sys     0m0.015s

c:\sed-windows>(c:\cygwin64\bin\bash -c "time cmd.exe /s /c \"\"sed-4.8-xp.exe \"N;s/\n/, /\" a.txt \> b.txt\"\"" )

real    0m1.123s
user    0m0.000s
sys     0m0.015s

c:\sed-windows>(c:\cygwin64\bin\bash -c "time cmd.exe /s /c \"\"sed-4.8-xp.exe \"N;s/\n/, /\" a.txt \> b.txt\"\"" )

real    0m0.936s
user    0m0.015s
sys     0m0.000s

3) for /l %i in (1,1,5) do (c:\cygwin64\bin\bash -c "time cmd.exe /s /c \"\"sed-4.8-x64.exe \"N;s/\n/, /\" a.txt \> b.txt\"\"")

c:\sed-windows>(c:\cygwin64\bin\bash -c "time cmd.exe /s /c \"\"sed-4.8-x64.exe \"N;s/\n/, /\" a.txt \> b.txt\"\"" )

real    0m1.638s
user    0m0.000s
sys     0m0.046s

c:\sed-windows>(c:\cygwin64\bin\bash -c "time cmd.exe /s /c \"\"sed-4.8-x64.exe \"N;s/\n/, /\" a.txt \> b.txt\"\"" )

real    0m1.201s
user    0m0.000s
sys     0m0.015s

c:\sed-windows>(c:\cygwin64\bin\bash -c "time cmd.exe /s /c \"\"sed-4.8-x64.exe \"N;s/\n/, /\" a.txt \> b.txt\"\"" )

real    0m1.014s
user    0m0.000s
sys     0m0.015s

c:\sed-windows>(c:\cygwin64\bin\bash -c "time cmd.exe /s /c \"\"sed-4.8-x64.exe \"N;s/\n/, /\" a.txt \> b.txt\"\"" )

real    0m0.920s
user    0m0.000s
sys     0m0.031s

c:\sed-windows>(c:\cygwin64\bin\bash -c "time cmd.exe /s /c \"\"sed-4.8-x64.exe \"N;s/\n/, /\" a.txt \> b.txt\"\"" )

real    0m0.796s
user    0m0.000s
sys     0m0.000s
```

**Comment by jack6th** [comment]
I tested with your code on Windows 10 64-bit 1903.  
sed-4.8-xp.exe:  
0.971, 1.032, 1.041, 0.970, 1.047  
mean: 1.012  
  
sed-4.8-x64.exe  
2.443, 2.674, 2.440, 2.435, 2.684  
mean: 2.535

**Comment by mbuilov** [comment]
Microsoft Windows [Version 10.0.16299.431], 64 bit

sed-4.8-xp.exe:
0.951, 0.823, 0.822, 0.851, 0.866, 0.986, 1.483, 1.038, 0.918, 0.928
mean: 0,967

sed-4.8-x64.exe:
0.701, 0.714, 0.660, 0.821, 0.813, 0.722, 0.607, 0.672, 0.544, 0.613
mean: 0,687

sed-4.8-x64.exe is faster than sed-4.8-xp.exe by 29% :)

It looks like Microsoft has changed something with the latest Windows updates.

**Comment by jack6th** [comment]
I inserted a line below @echo off   
`set LC_ALL=C`  
Now sed-4.8-x64.exe is faster than sed-4.8-xp.exe  
   
Perhaps Windows will auto do some encoding convertion if the default code page is not 1 byte per character, though the file is a pure ascii file.

**Comment by mbuilov** [comment]
Thank you so much for testing!
I can confirm the issue (running from cygwin bash):

```
{ time ./sed-4.8-x64.exe --locale="ru-RU" "N;s/\n/, /" a.txt > b.txt; } 2>&1 | grep real
real 0m0,094s

{ time ./sed-4.8-x64.exe --locale="zh-CN" "N;s/\n/, /" a.txt > b.txt; } 2>&1 | grep real
real 0m4,867s
```

The cause of slowdown is that internally sed needs to count multibyte characters in the processed file (sed interprets characters in the file according to chosen locale).
And counting characters in locales with MB_CUR_MAX > 1 involves calling system function mbtowc(), which is costly.

By default, windows applications use the system default locale - which is set on "Language for non-Unicode programs" property page (of the Region and Language window).

But sed also checks for LC_... and LANG environment variables (like in UNIX-like OSes), if locale wasn't explicitly specified by the "--locale" command-line option.

So, if you know that input file is encoded in ASCII, you should use the sed option “--locale=C” (or set the environment variable LC_ALL=C, as you did above).
