### ISSUE TITLE
Single quotes in pattern not supported

### ISSUE THREAD

**Issue by orbanbalage** [mbuilov/sed-windows#8]
```
>echo 'string=abc' | sed "s/=//"
'stringabc'
>echo 'string=abc' | sed 's/=//'
C:\ProgramData\chocolatey\lib\sed\tools\install\sed.exe: -e expression #1, char 1: unknown command: `''
>sed --version
C:\ProgramData\chocolatey\lib\sed\tools\install\sed.exe (GNU sed) 4.8
```
Maybe this is a Windows thing, but it would be nice to have the same syntax in linux working here as well.

**Comment by mbuilov** [comment]
Thanks for the suggestion.
But I see no way how this can be done.

Quotation marks are parsed by the command-line interpreter (shell) even
before sed is called.
On UNIX, this is usually the POSIX shell; on Windows, this is cmd.exe.

For example, when trying to execute:
C:\sed.exe 's/a/&/' some_file

cmd.exe will call sed with one argument:
's/a/

and the remainder
/' some_file

cmd.exe will try to interpret as a separate command.


PS.

1) On Windows, parsing the command line is quite complicated, see
https://stackoverflow.com/questions/4094699/how-does-the-windows-command-interpreter-cmd-exe-parse-scripts

2) When cmd.exe starts a program, cmd.exe passes arguments to it in the
form of a single line, which C/C++ programs usually break into separate
arguments - see
https://docs.microsoft.com/en-us/previous-versions/17w5ykft(v=vs.85)

**Comment by orbanbalage** [comment]
re: 1) - oh wow!

It seems one statement there answers my second question (which was the trigger of this issue anyway)...

> It is not possible to escape the closing quote.

ie. it is not possible to use a pattern with sed, where the replacement character would be a double-quote character (becase there is no way to escape the same character, nor is there a possibility to use single quotes for the whole string, as in linux):

`sed 's/=/"/'`

**Comment by mbuilov** [comment]
> ie. it is not possible to use a pattern with sed, where the replacement
character would be a double-quote character (becase there is no way to
escape the same character, nor is there a possibility to use single quotes
for the whole string, as in linux):

Not quite correct :)


1) Double-quotes can escaped with two double quotes:

c:\User\sed-windows>echo "1" | sed-4.8-x64.exe "s/""/=/g"
=1=

2) Also, double-quotes can be escaped by backslash:

c:\User\sed-windows>echo "1" | sed-4.8-x64.exe "s/\"/=/g"
=1=

3) But, cmd.exe does not like unpaired double quotes:

c:\User\sed-windows>echo "1" | sed-4.8-x64.exe "s/""/=/g" && echo a
=1=
a

c:\User\sed-windows>echo "1" | sed-4.8-x64.exe "s/\"/=/g" && echo a
sed-4.8-x64.exe: can't read &&: No such file or directory
sed-4.8-x64.exe: can't read echo: No such file or directory
sed-4.8-x64.exe: can't read a: No such file or directory
